package testgroup.filmography.util;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import java.security.NoSuchAlgorithmException;

import static testgroup.filmography.util.Converter.toHexString;
import static testgroup.filmography.util.Converter.getSHA;

public class PasswordConverterExample {
    public static void main(String[] args) {
        String userPassword = "user12345";
        String adminPassword = "admin12345";
        String s2 = "TeachMeSkills";
        try
        {
            System.out.println("HashCode Generated by SHA-256 for:");
            System.out.println("\n" + userPassword + " : " + toHexString(getSHA(userPassword)));
            System.out.println("\n" + s2 + " : " + toHexString(getSHA(s2)));
        }
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            System.out.println("Exception thrown for incorrect algorithm: " + e);
        }

        BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
        String encodedUserPassword = passwordEncoder.encode(userPassword);
        System.out.println();
        System.out.println("UserPassword is : " + encodedUserPassword);

        String encodedAdminPassword = passwordEncoder.encode(adminPassword);
        System.out.println();
        System.out.println("AdminPassword is : " + encodedAdminPassword);

        boolean isEncodedS1Match = passwordEncoder.matches(userPassword,encodedUserPassword);
        System.out.println("S1 : " + userPassword + " isS1Matched :" + isEncodedS1Match);
    }
}
